name = "zika-push"
account_id = "d0ae60ae49a7c6fe01b16b31bdba0926"
main = "worker.js"
compatibility_date = "2026-08-01"

[triggers]
crons = ["*/30 * * * *"]

[vars]
VAPID_PUBLIC = "BNlUK3R6LYQzrryHsvr6D8YZ2XAVvfsvsBJzyRK1ANnE54aPT2YjCOv7qoxVWhZoZOgX9NHB-AnycRFCbc4MasI"

[[kv_namespaces]]
binding = "SUBS"
id = "bb4424975b8146efbdb5205608e778d8"
